name: testing
on: [push, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo 'Dave is awesome!!!'
      - name: step 2
        run: echo 'This is step 2'
